### ISSUE TITLE
Wiring Schematic/Diagram for connecting components

### ISSUE THREAD

**Issue by abhishektrip** [veebch/thedailygrind#1]
First of all - thanks for doing this!

Would you be able to share the wiring diagram for all the components please? This is my first electronics project and I'm pretty lost as to how I connect everything together. 

Any diagrams would be super helpful. 
I have all the components listed in the readme.

**Comment by veebch** [comment]
Hey! And well done on jumping in with both feet!

I will update the readme to include a wiring diagram. Also, free to ask as many questions as you want here. You'll definitely be able to help improve the documentation by finding out where the instructions could be improved.

**Comment by veebch** [comment]
I've added a list of all the connections to the README. 
EDIT: I'm leaving this open for now so you can tell me what other bits I can add....

**Comment by abhishektrip** [comment]
Wow, this is super helpful. 

I have a follow-up questions
- https://github.com/veebch/thedailygrind/blob/7b7d5da3ec8cb1dd596f8fe88bbd773f4f5a0239/main.py#L39 setsup Pin 16 as MISO but there is no connection in the OLED display to connect to Pin 16. Basically, Pin 16 is not connected . Is that correct? 

- You mention in the README
> Motor Driver: Waveshare DC motor board for Pico (jumpers soldered for I2C 1 to avoid screen issues due to pin use)

What does this mean? I have a feeling this is probably something very basic that I'm not aware of :( 

- I've been using the USB connection on the Pico to power the setup but you use a 12V DC power. Will using the USB connection work? I also use the USB connection to run & debug the program. Feeling a little lost here

**Comment by veebch** [comment]
That lost feeling is all part of the fun :) Don't give up...... you'll get there.

- Pin 16. Ignore it. It isn't used. I will delete it.

- The jumper bit is a physical setting that I did to avoid the pins the DC board was using clashing with the other components. In hindsight, I may have been able to do it differently.....The jumpers are under where the Pico fits onto the board. You can see them on the photo on the [waveshare wiki](https://www.waveshare.com/wiki/Pico-Motor-Driver). You can google around on removing jumpers (also called zero ohm resistors) ..... this was the first hit I came across: https://www.youtube.com/watch?v=r9UXlelPDPM

- The motor will run just using USB, but it runs faster(and stronger) with a bit more juice. The one in the link is the one I use and has been going for a year with no isssues.

Hope this helps.... keep the questions coming!

**Comment by abhishektrip** [comment]
Unfortunately, I can't get the pico-motor-driver to work. 

It keeps giving me `OSError: [Errno 5] EIO` on write. I've been trying to debug the issue but apparently `i2c.scan()` returns an empty array. Didn't find much info on forums etc but the few forum posts that did find say there is connection issue. 
I did get a stepper motor working so that's some progress. 

Also, can't get the OLED display to get working either. Tried both using the pico-motor-driver and directly connecting to the pico but no luck their either. I even got a replacement screen but both didn't work. 

I'm probably going to give up on the dc-motor driver and the Oled screen for now and just get the rotary encoder working with stepper motor.

**Comment by veebch** [comment]
Did you remove the jumpers? I vaguely recall seeing EIO errors when the i2c for the rotary encoder was clashing with the DC board, This is a vague memory, so I could be wrong. 

I checked the OLED/ rotary encoder stuff yesterday and got it working from the instructions on fresh hardware. This suggests that the error you're running into is something to do with the DC board, or as you say, a connection issue. 

Keep it up! Almost there  :)

EDIT: PS I added a missing file `color_setup.py` to the repository, which is needed to start the OLED. If you've not got this, add it....

**Comment by abhishektrip** [comment]
Alright, good news - everything now works! I soldered the pins to pico ( was using solder-less pins) + ditched the breadboard and now everything works. 

Made a few changes to the pin configuration


| [Pico GPIO](https://www.elektronik-kompendium.de/sites/raspberry-pi/bilder/raspberry-pi-pico-gpio.png) | OLED |
|-----------|------|
|   11       | DIN/MOSI  |
|   10      | CLK/SCK  |
|   13      | CS  |
|   15       | DC  |
|   14      | RST  |


| [Pico GPIO](https://www.elektronik-kompendium.de/sites/raspberry-pi/bilder/raspberry-pi-pico-gpio.png) | DC-Motor-Driver|
|-----------|------|
|   21       | SDL  |
|   20      | SCA  |

This uses the default I2C0 on the dc-motor-driver. These pin configurations let me use the board directly without soldering the jumpers.

**Comment by veebch** [comment]
That is excellent! Congratulations! It's a good feeling when tenacity pays off.

I think changing the pins is a good idea. I will close this issue for now and add changing the pins to my to-do list. You are of course welcome to fork the repository and then submit a pull request :)
